services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./volumes/cache:/data
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # maps lhost:container
    ports:
      - '5430:5432'
    volumes:
      - ./volumes/data:/data/db
  api:
    container_name: ethereum-tracker-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    # env_file: .env
    # maps lhost:container
    ports:
      - '3001:3000'
    depends_on:
      - postgres
      - redis
