services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./volumes/cache:/data
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    # env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # lhost:container
    ports:
      - '5430:5432'
    volumes:
      - ./volumes/data:/data/db
  api:
    container_name: ethereum-tracker-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # lhost:container
    ports:
      - '3001:3000'
    depends_on:
      - postgres
      - redis
