name: Node.js CI

on: [push, pull_request]

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm install --global npm@11.10.1
      - run: npm ci
      - run: npm run prettify:check
      - run: npm run eslint
      - run: npm run build
      - run: npm run typecheck:tests

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm install --global npm@11.10.1
      - run: npm ci
      - run: npm test -- --runInBand
